import Head from "next/head";
import AboutUs from "../components/AboutUs";
import Layout from "../components/Layout";
import Main from "../components/layout/Main";


export default function Home() {
  return (
    <>
      <Head>
        <title>Climax Music Empire</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/CLIMAXMUSICLOGOv3.png" />
      </Head>
      <Layout />
      <AboutUs />
      <Main />
    </>
  );
}
