import Head from "next/head";
import Artist from "../components/Artist";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Climax Music Empire</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/CLIMAXMUSICLOGOv3.png" />
      </Head>
      <Layout />
      <Artist />
    </>
  );
}
